// <auto-generated />
using System;
using GateManagementApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GateManagementApi.Migrations
{
    [DbContext(typeof(GateManagementEventDbContext))]
    [Migration("20210523191630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GateManagementApi.Domain.Aggregate.GateAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gate");
                });

            modelBuilder.Entity("GateManagementApi.Domain.Aggregate.TicketAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("GateManagementApi.Domain.Core.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventData")
                        .HasColumnType("text");

                    b.Property<string>("GateAggregateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketAggregateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateAggregateId");

                    b.HasIndex("TicketAggregateId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("GateManagementApi.Domain.Core.Event", b =>
                {
                    b.HasOne("GateManagementApi.Domain.Aggregate.GateAggregate", null)
                        .WithMany("Events")
                        .HasForeignKey("GateAggregateId");

                    b.HasOne("GateManagementApi.Domain.Aggregate.TicketAggregate", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketAggregateId");
                });

            modelBuilder.Entity("GateManagementApi.Domain.Aggregate.GateAggregate", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GateManagementApi.Domain.Aggregate.TicketAggregate", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
