// <auto-generated />
using System;
using CustomerManagementApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerManagementApi.Migrations
{
    [DbContext(typeof(CustomerManagementEventDbContext))]
    [Migration("20210523191216_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerManagementApi.Domain.Aggregates.CustomerAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CustomerManagementApi.Domain.Core.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerAggregateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventData")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAggregateId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("CustomerManagementApi.Domain.Core.Event", b =>
                {
                    b.HasOne("CustomerManagementApi.Domain.Aggregates.CustomerAggregate", null)
                        .WithMany("Events")
                        .HasForeignKey("CustomerAggregateId");
                });

            modelBuilder.Entity("CustomerManagementApi.Domain.Aggregates.CustomerAggregate", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
